blank_issues_enabled: false
contact_links:
  - name: Cryptomator Community
    url: https://community.cryptomator.org/
    about: Please ask and answer questions here
  - name: Documentation
    url: https://docs.cryptomator.org/
    about: Get instructions on how to use Cryptomator
